root = rprojroot::find_root(rprojroot::is_git_root)
adult_train = data.table::fread(file.path(root, "data-raw", "adult-test-raw.csv"))
adult_test = data.table::fread(file.path(root, "data-raw", "adult-train-raw.csv"))
rda_path = base::file.path(root, "data", "adult.rda")
base::save(adult_test, adult_train, file = rda_path)
