test_that("unloading leaves no trace", {
  total_learners = length(mlr_learners$keys())
  total_tasks = length(mlr_tasks$keys())
  total_measures = length(mlr_measures$keys())
  total_pipeops= length(mlr_pipeops$keys())
  library("mlr3fairness")
  unloadNamespace("mlr3fairness")
  base_learners = length(mlr_learners$keys())
  base_tasks = length(mlr_tasks$keys())
  base_measures = length(mlr_measures$keys())
  base_pipeops = length(mlr_pipeops$keys())
  expect_true(base_learners == total_learners)
  expect_true(base_tasks ==  total_tasks)
  expect_true(base_measures == total_measures)
  expect_true(base_pipeops == total_pipeops)
})